markdown: kramdown
url: 'https://alple-sec.github.io'
baseurl: null
title: Alple
description: Accessible Security & Privacy
site-image: /alple-sec.github.io/assets/images/meta.jpg
site-keywords: 'Cybersecurity, Blog, Privacy'
favicon-url: >-
  https://github.com/alple-sec/alple-sec.github.io/blob/master/assets/images/smallPhoenix.png.png?raw=true
heroimage: >-
  https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
email: info@alple.xyz
facebook_username: null
twitter_username: alple-sec
instagram_username: null
linkedin_username: null
github_username: alple-sec
youtube_channel_id: null
reddit_username: null
behance_username: null
dribbble_username: null
spotify_username: null
google-analytics: G-Q0CTE2QPWJ
disqus-shortname: null
author-name: Alple
author-image: >-
  https://github.com/alple-sec/alple-sec.github.io/blob/master/assets/images/phoenix.png.png?raw=true
author-about: >-
  Hey! I'm a full-time student, doing all things Cybersecurity and web design. I
  also write about online security and privacy and cover weekly IT news. If that
  interests you, check out my blog! If you have some questions, feel free to
  message me on discord!
author-url: 'https://github.com/alple-sec/'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
